export const SOUNDCLOUD_TRACKS = [
  {
    id: "the-sleepers-waking",
    title: "The Sleepers Waking",
    soundId: "2403987975",
    slug: "the-sleepers-waking",
    image: "/images/tracks/the-sleepers-waking.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-sleepers-waking",
    recorded: "September 2026",
  },
  {
    id: "fragile-god",
    title: "Fragile God",
    soundId: "2403226194",
    slug: "fragile-god",
    image: "/images/tracks/fragile-god.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/fragile-god",
    recorded: "September 2026",
  },
  {
    id: "wait-for-a-love-that-stays",
    title: "Wait for a Love That Stays",
    soundId: "2403207720",
    slug: "wait-for-a-love-that-stays",
    image: "/images/tracks/wait-for-a-love-that-stays.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/wait-for-a-love-that-stays",
    recorded: "September 2026",
  },
  {
    id: "now-i-see-you-blossom",
    title: "Now I See You Blossom",
    soundId: "2402533866",
    slug: "now-i-see-you-blossom",
    image: "/images/tracks/now-i-see-you-blossom.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/now-i-see-you-blossom",
    recorded: "September 2026",
  },
  {
    id: "the-endless-mirror",
    title: "The Endless Mirror",
    soundId: "2367666410",
    slug: "the-endless-mirror",
    image: "/images/tracks/the-endless-mirror.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-endless-mirror",
    recorded: "July 2026",
  },
  {
    id: "old-mens-game",
    title: "Old Men's Game",
    soundId: "2367489638",
    slug: "old-mens-game",
    image: "/images/tracks/old-mens-game.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/old-mens-game",
    recorded: "July 2026",
  },
  {
    id: "me-and-eric",
    title: "Me and Eric",
    soundId: "2366726657",
    slug: "me-and-eric",
    image: "/images/tracks/me-and-eric.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/me-and-eric",
    recorded: "July 2026",
  },
  {
    id: "fake-love-shadows",
    title: "Fake Love Shadows",
    soundId: "2359578329",
    slug: "fake-love-shadows",
    image: "/images/tracks/fake-love-shadows.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/fake-love-shadows",
    recorded: "July 2026",
  },
  {
    id: "bassline-serenade",
    title: "Bassline Serenade",
    soundId: "2356133381",
    slug: "bassline-serenade",
    image: "/images/tracks/bassline-serenade.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/bassline-serenade",
    recorded: "July 2026",
  },
  {
    id: "dont-look-up",
    title: "Don't Look Up",
    soundId: "2356129175",
    slug: "dont-look-up",
    image: "/images/tracks/dont-look-up.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/dont-look-up",
    recorded: "July 2026",
  },
  {
    id: "whats-in-it-for-me",
    title: "What's In It For Me",
    soundId: "2356128029",
    slug: "whats-in-it-for-me",
    image: "/images/tracks/whats-in-it-for-me.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/whats-in-it-for-me",
    recorded: "July 2026",
  },
  {
    id: "nobody-can-stop-it",
    title: "Nobody Can Stop It",
    soundId: "2355582143",
    slug: "nobody-can-stop-it",
    image: "/images/tracks/nobody-can-stop-it.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/nobody-can-stop-it",
    recorded: "July 2026",
  },
  {
    id: "djinn",
    title: "Djinn",
    soundId: "2350836482",
    slug: "djinn",
    image: "/images/tracks/djinn.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/djinn",
    recorded: "June 2026",
  },
  {
    id: "subterranean-pulse",
    title: "Subterranean Pulse",
    soundId: "2350836317",
    slug: "subterranean-pulse",
    image: "/images/tracks/subterranean-pulse.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/subterranean-pulse",
    recorded: "June 2026",
  },
  {
    id: "neon-nostalgia",
    title: "Neon Nostalgia",
    soundId: "2350836179",
    slug: "neon-nostalgia",
    image: "/images/tracks/neon-nostalgia.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/neon-nostalgia",
    recorded: "June 2026",
  },
  {
    id: "neon-pulse",
    title: "Neon Pulse",
    soundId: "2350836059",
    slug: "neon-pulse",
    image: "/images/tracks/neon-pulse.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/neon-pulse",
    recorded: "June 2026",
  },
  {
    id: "shamanic-in-the-woods",
    title: "Shamanic in the Woods",
    soundId: "2349450206",
    slug: "shamanic-in-the-woods",
    image: "/images/tracks/shamanic-in-the-woods.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/shamanic-in-the-woods",
    recorded: "June 2026",
  },
  {
    id: "shamanica",
    title: "Shamanica",
    soundId: "2349449951",
    slug: "shamanica",
    image: "/images/tracks/shamanica.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/shamanica",
    recorded: "June 2026",
  },
  {
    id: "shamanic-me-up",
    title: "Shamanic Me Up",
    soundId: "2349449819",
    slug: "shamanic-me-up",
    image: "/images/tracks/shamanic-me-up.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/shamanic-me-up",
    recorded: "June 2026",
  },
  {
    id: "the-worst-kind-of-heartache",
    title: "The Worst Kind of Heartache",
    soundId: "2345453567",
    slug: "the-worst-kind-of-heartache",
    image: "/images/tracks/the-worst-kind-of-heartache.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-worst-kind-of-heartache",
    recorded: "June 2026",
  },
  {
    id: "i-tired",
    title: "I Tired",
    soundId: "2345452907",
    slug: "i-tired",
    image: "/images/tracks/i-tired.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/i-tired",
    recorded: "June 2026",
  },
  {
    id: "solitudes-silent-flame",
    title: "Solitude’s Silent Flame",
    soundId: "2343392219",
    slug: "solitudes-silent-flame",
    image: "/images/tracks/solitudes-silent-flame.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/solitudes-silent-flame",
    recorded: "June 2026",
  },
  {
    id: "hold-lightly",
    title: "Hold Lightly",
    soundId: "2342719901",
    slug: "hold-lightly",
    image: "/images/tracks/hold-lightly.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/hold-lightly",
    recorded: "June 2026",
  },
  {
    id: "marble-heartbeats",
    title: "Marble Heartbeats",
    soundId: "2339661584",
    slug: "marble-heartbeats",
    image: "/images/tracks/marble-heartbeats.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/marble-heartbeats",
    recorded: "June 2026",
  },
  {
    id: "7-signs-silent-danger",
    title: "7 Signs ( Silent Danger)",
    soundId: "2339649290",
    slug: "7-signs-silent-danger",
    image: "/images/tracks/7-signs-silent-danger.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/7-signs-silent-danger",
    recorded: "June 2026",
  },
  {
    id: "bones-keep-score",
    title: "Bones Keep Score",
    soundId: "2338518863",
    slug: "bones-keep-score",
    image: "/images/tracks/bones-keep-score.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/bones-keep-score",
    recorded: "June 2026",
  },
  {
    id: "broken-brick-rebuild",
    title: "Broken Brick Rebuild",
    soundId: "2337122255",
    slug: "broken-brick-rebuild",
    image: "/images/tracks/broken-brick-rebuild.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/broken-brick-rebuild",
    recorded: "June 2026",
  },
  {
    id: "half-way-heart-mp3",
    title: "Half Way Heart",
    soundId: "2336609126",
    slug: "half-way-heart-mp3",
    image: "/images/tracks/half-way-heart-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/half-way-heart-mp3",
    recorded: "June 2026",
  },
  {
    id: "miles-of-lies",
    title: "Miles of Lies",
    soundId: "2334325169",
    slug: "miles-of-lies",
    image: "/images/tracks/miles-of-lies.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/miles-of-lies",
    recorded: "June 2026",
  },
  {
    id: "makers-make",
    title: "Makers Make",
    soundId: "2333772470",
    slug: "makers-make",
    image: "/images/tracks/makers-make.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/makers-make",
    recorded: "June 2026",
  },
  {
    id: "that-sax-is-fine",
    title: "That Sax Is Fine",
    soundId: "2330840912",
    slug: "that-sax-is-fine",
    image: "/images/tracks/that-sax-is-fine.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/that-sax-is-fine",
    recorded: "May 2026",
  },
  {
    id: "two-blue-screens",
    title: "Two Blue Screens",
    soundId: "2330653088",
    slug: "two-blue-screens",
    image: "/images/tracks/two-blue-screens.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/two-blue-screens",
    recorded: "May 2026",
  },
  {
    id: "throat-sing",
    title: "Throat Sing",
    soundId: "2330652548",
    slug: "throat-sing",
    image: "/images/tracks/throat-sing.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/throat-sing",
    recorded: "May 2026",
  },
  {
    id: "piano-hands",
    title: "Piano Hands",
    soundId: "2330648294",
    slug: "piano-hands",
    image: "/images/tracks/piano-hands.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/piano-hands",
    recorded: "May 2026",
  },
  {
    id: "bonefire-circle",
    title: "Bonefire Circle",
    soundId: "2330647004",
    slug: "bonefire-circle",
    image: "/images/tracks/bonefire-circle.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/bonefire-circle",
    recorded: "May 2026",
  },
  {
    id: "quartz-pulse-ritual",
    title: "Quartz Pulse Ritual",
    soundId: "2330645792",
    slug: "quartz-pulse-ritual",
    image: "/images/tracks/quartz-pulse-ritual.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/quartz-pulse-ritual",
    recorded: "May 2026",
  },
  {
    id: "saxatone",
    title: "Saxatone",
    soundId: "2330382857",
    slug: "saxatone",
    image: "/images/tracks/saxatone.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/saxatone",
    recorded: "May 2026",
  },
  {
    id: "babushka-on-fire",
    title: "Babushka on Fire",
    soundId: "2330320646",
    slug: "babushka-on-fire",
    image: "/images/tracks/babushka-on-fire.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/babushka-on-fire",
    recorded: "May 2026",
  },
  {
    id: "dusty-shoe-bass",
    title: "Dusty Shoe Bass",
    soundId: "2330237195",
    slug: "dusty-shoe-bass",
    image: "/images/tracks/dusty-shoe-bass.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/dusty-shoe-bass",
    recorded: "May 2026",
  },
  {
    id: "scratch-on-the-floor",
    title: "Scratch on the Floor",
    soundId: "2330211728",
    slug: "scratch-on-the-floor",
    image: "/images/tracks/scratch-on-the-floor.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/scratch-on-the-floor",
    recorded: "May 2026",
  },
  {
    id: "let-that-fear-go",
    title: "Let That Fear Go",
    soundId: "2330217656",
    slug: "let-that-fear-go",
    image: "/images/tracks/let-that-fear-go.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/let-that-fear-go",
    recorded: "May 2026",
  },
  {
    id: "the-last-one",
    title: "The Last One",
    soundId: "2325143357",
    slug: "the-last-one",
    image: "/images/tracks/the-last-one.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-last-one",
    recorded: "May 2026",
  },
  {
    id: "paper-crown",
    title: "Paper Crown",
    soundId: "2325138953",
    slug: "paper-crown",
    image: "/images/tracks/paper-crown.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/paper-crown",
    recorded: "May 2026",
  },
  {
    id: "gold-curtains",
    title: "Gold Curtains",
    soundId: "2325132605",
    slug: "gold-curtains",
    image: "/images/tracks/gold-curtains.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/gold-curtains",
    recorded: "May 2026",
  },
  {
    id: "spy-pigeons",
    title: "Spy Pigeons",
    soundId: "2317150040",
    slug: "spy-pigeons",
    image: "/images/tracks/spy-pigeons.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/spy-pigeons",
    recorded: "May 2026",
  },
  {
    id: "bank-holiday-bloke",
    title: "Bank Holiday Bloke",
    soundId: "2313685907",
    slug: "bank-holiday-bloke",
    image: "/images/tracks/bank-holiday-bloke.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/bank-holiday-bloke",
    recorded: "May 2026",
  },
  {
    id: "steel-peach-bloom",
    title: "Steel Peach Bloom",
    soundId: "2313685787",
    slug: "steel-peach-bloom",
    image: "/images/tracks/steel-peach-bloom.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/steel-peach-bloom",
    recorded: "May 2026",
  },
  {
    id: "saxamoan",
    title: "Saxamoan",
    soundId: "2313001223",
    slug: "saxamoan",
    image: "/images/tracks/saxamoan.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/saxamoan",
    recorded: "May 2026",
  },
  {
    id: "lift-me-up",
    title: "Lift Me Up",
    soundId: "2312995808",
    slug: "lift-me-up",
    image: "/images/tracks/lift-me-up.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/lift-me-up",
    recorded: "May 2026",
  },
  {
    id: "natures-plant",
    title: "Natures Plant",
    soundId: "2312993204",
    slug: "natures-plant",
    image: "/images/tracks/natures-plant.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/natures-plant",
    recorded: "May 2026",
  },
  {
    id: "stone-chest",
    title: "Stone Chest",
    soundId: "2312992352",
    slug: "stone-chest",
    image: "/images/tracks/stone-chest.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/stone-chest",
    recorded: "May 2026",
  },
  {
    id: "pocketful-umbrellas",
    title: "Pocketful Umbrellas",
    soundId: "2312991761",
    slug: "pocketful-umbrellas",
    image: "/images/tracks/pocketful-umbrellas.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/pocketful-umbrellas",
    recorded: "May 2026",
  },
  {
    id: "dodgy-sir-keir-scandal-after",
    title: "Dodgy Sir Keir (scandal After Scandal)",
    soundId: "2311215506",
    slug: "dodgy-sir-keir-scandal-after",
    image: "/images/tracks/dodgy-sir-keir-scandal-after.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/dodgy-sir-keir-scandal-after",
    recorded: "April 2026",
  },
  {
    id: "thats-life",
    title: "That’s Life",
    soundId: "2311214747",
    slug: "thats-life",
    image: "/images/tracks/thats-life.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/thats-life",
    recorded: "April 2026",
  },
  {
    id: "moonlit-handpan-groove-mp3",
    title: "Moonlit Handpan Groove",
    soundId: "2300819651",
    slug: "moonlit-handpan-groove-mp3",
    image: "/images/tracks/moonlit-handpan-groove-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/moonlit-handpan-groove-mp3",
    recorded: "April 2026",
  },
  {
    id: "broken-britain-debt-bomb",
    title: "Broken Britain Debt Bomb",
    soundId: "2300818835",
    slug: "broken-britain-debt-bomb",
    image: "/images/tracks/broken-britain-debt-bomb.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/broken-britain-debt-bomb",
    recorded: "April 2026",
  },
  {
    id: "mo-bius-bowl-mp3",
    title: "Möbius Bowl",
    soundId: "2300816111",
    slug: "mo-bius-bowl-mp3",
    image: "/images/tracks/mo-bius-bowl-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/mo-bius-bowl-mp3",
    recorded: "April 2026",
  },
  {
    id: "moon-circles-1",
    title: "Moon Circles",
    soundId: "2300815685",
    slug: "moon-circles-1",
    image: "/images/tracks/moon-circles-1.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/moon-circles-1",
    recorded: "April 2026",
  },
  {
    id: "bamboo-kickback",
    title: "Bamboo Kickback",
    soundId: "2300365199",
    slug: "bamboo-kickback",
    image: "/images/tracks/bamboo-kickback.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/bamboo-kickback",
    recorded: "April 2026",
  },
  {
    id: "nine-completes",
    title: "Nine Completes",
    soundId: "2300363972",
    slug: "nine-completes",
    image: "/images/tracks/nine-completes.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/nine-completes",
    recorded: "April 2026",
  },
  {
    id: "shadows-of-the-cross",
    title: "Shadows of the Cross",
    soundId: "2296846394",
    slug: "shadows-of-the-cross",
    image: "/images/tracks/shadows-of-the-cross.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/shadows-of-the-cross",
    recorded: "April 2026",
  },
  {
    id: "tracy-chapman-tape",
    title: "Tracy Chapman Tape",
    soundId: "2296477196",
    slug: "tracy-chapman-tape",
    image: "/images/tracks/tracy-chapman-tape.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/tracy-chapman-tape",
    recorded: "April 2026",
  },
  {
    id: "welcome-home-neville",
    title: "Welcome Home Neville",
    soundId: "2296440245",
    slug: "welcome-home-neville",
    image: "/images/tracks/welcome-home-neville.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/welcome-home-neville",
    recorded: "April 2026",
  },
  {
    id: "mirror-mirror-left-wing",
    title: "Mirror, Mirror Left Wing Nutters",
    soundId: "2293084733",
    slug: "mirror-mirror-left-wing",
    image: "/images/tracks/mirror-mirror-left-wing.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/mirror-mirror-left-wing",
    recorded: "March 2026",
  },
  {
    id: "ego-overload-mp3",
    title: "Ego Overload",
    soundId: "2293074236",
    slug: "ego-overload-mp3",
    image: "/images/tracks/ego-overload-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/ego-overload-mp3",
    recorded: "March 2026",
  },
  {
    id: "quantum-stage",
    title: "Quantum Stage",
    soundId: "2292575807",
    slug: "quantum-stage",
    image: "/images/tracks/quantum-stage.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/quantum-stage",
    recorded: "March 2026",
  },
  {
    id: "fiat-slaves-no-more",
    title: "Fiat Slaves No More",
    soundId: "2292541793",
    slug: "fiat-slaves-no-more",
    image: "/images/tracks/fiat-slaves-no-more.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/fiat-slaves-no-more",
    recorded: "March 2026",
  },
  {
    id: "find-your-atman",
    title: "Find Your Atman",
    soundId: "2292205376",
    slug: "find-your-atman",
    image: "/images/tracks/find-your-atman.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/find-your-atman",
    recorded: "March 2026",
  },
  {
    id: "baguio-the-wrong-dam-room-mp3",
    title: "Baguio the Wrong Dam Room",
    soundId: "2267008139",
    slug: "baguio-the-wrong-dam-room-mp3",
    image: "/images/tracks/baguio-the-wrong-dam-room-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/baguio-the-wrong-dam-room-mp3",
    recorded: "February 2026",
  },
  {
    id: "the-city-of-london",
    title: "The City of London",
    soundId: "2254053998",
    slug: "the-city-of-london",
    image: "/images/tracks/the-city-of-london.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-city-of-london",
    recorded: "January 2026",
  },
  {
    id: "when-we-were-cool",
    title: "When We Were Cool",
    soundId: "2254035665",
    slug: "when-we-were-cool",
    image: "/images/tracks/when-we-were-cool.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/when-we-were-cool",
    recorded: "January 2026",
  },
  {
    id: "awake",
    title: "Awake",
    soundId: "2254011254",
    slug: "awake",
    image: "/images/tracks/awake.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/awake",
    recorded: "January 2026",
  },
  {
    id: "the-mushroom-alchemist",
    title: "The Mushroom Alchemist",
    soundId: "2254002086",
    slug: "the-mushroom-alchemist",
    image: "/images/tracks/the-mushroom-alchemist.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-mushroom-alchemist",
    recorded: "January 2026",
  },
  {
    id: "your-first-pill",
    title: "Your First Pill",
    soundId: "2253504422",
    slug: "your-first-pill",
    image: "/images/tracks/your-first-pill.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/your-first-pill",
    recorded: "January 2026",
  },
  {
    id: "mr-oil-up-aaron-mp3",
    title: "Mr. Oil Up Aaron",
    soundId: "2252276207",
    slug: "mr-oil-up-aaron-mp3",
    image: "/images/tracks/mr-oil-up-aaron-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/mr-oil-up-aaron-mp3",
    recorded: "January 2026",
  },
  {
    id: "cockny-in-his-polish-tracksuit",
    title: "Cockny in His Polish Tracksuit",
    soundId: "2251604471",
    slug: "cockny-in-his-polish-tracksuit",
    image: "/images/tracks/cockny-in-his-polish-tracksuit.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/cockny-in-his-polish-tracksuit",
    recorded: "January 2026",
  },
  {
    id: "the-best-of-the-worst-mp3",
    title: "The Best of the Worst",
    soundId: "2251534232",
    slug: "the-best-of-the-worst-mp3",
    image: "/images/tracks/the-best-of-the-worst-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/the-best-of-the-worst-mp3",
    recorded: "January 2026",
  },
  {
    id: "famous-aint-fun-anymore",
    title: "Famous Ain’t Fun Anymore",
    soundId: "2251045757",
    slug: "famous-aint-fun-anymore",
    image: "/images/tracks/famous-aint-fun-anymore.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/famous-aint-fun-anymore",
    recorded: "January 2026",
  },
  {
    id: "through-the-cracks",
    title: "Through the Cracks",
    soundId: "2251040450",
    slug: "through-the-cracks",
    image: "/images/tracks/through-the-cracks.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/through-the-cracks",
    recorded: "January 2026",
  },
  {
    id: "baguio-trip-mp3",
    title: "Baguio Trip",
    soundId: "2251037480",
    slug: "baguio-trip-mp3",
    image: "/images/tracks/baguio-trip-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/baguio-trip-mp3",
    recorded: "January 2026",
  },
  {
    id: "remember-who-you-are-mp3-1",
    title: "Remember-who-you Are V2",
    soundId: "2251003727",
    slug: "remember-who-you-are-mp3-1",
    image: "/images/tracks/remember-who-you-are-mp3-1.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/remember-who-you-are-mp3-1",
    recorded: "January 2026",
  },
  {
    id: "hyperdimensional-dancefloor",
    title: "Hyperdimensional Dancefloor",
    soundId: "2251002107",
    slug: "hyperdimensional-dancefloor",
    image: "/images/tracks/hyperdimensional-dancefloor.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/hyperdimensional-dancefloor",
    recorded: "January 2026",
  },
  {
    id: "remember-who-you-are-mp3",
    title: "Remember Who You Are",
    soundId: "2250999269",
    slug: "remember-who-you-are-mp3",
    image: "/images/tracks/remember-who-you-are-mp3.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/remember-who-you-are-mp3",
    recorded: "January 2026",
  },
  {
    id: "infinite-spark-of-atoms-1",
    title: "Infinite Spark of Atoms",
    soundId: "2250977942",
    slug: "infinite-spark-of-atoms-1",
    image: "/images/tracks/infinite-spark-of-atoms-1.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/infinite-spark-of-atoms-1",
    recorded: "January 2026",
  },
  {
    id: "infinite-spark-of-atoms",
    title: "Infinite Spark of Atoms",
    soundId: "2250975818",
    slug: "infinite-spark-of-atoms",
    image: "/images/tracks/infinite-spark-of-atoms.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/infinite-spark-of-atoms",
    recorded: "January 2026",
  },
  {
    id: "puppets-on-a-string",
    title: "Puppets on a String",
    soundId: "2250962978",
    slug: "puppets-on-a-string",
    image: "/images/tracks/puppets-on-a-string.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/puppets-on-a-string",
    recorded: "January 2026",
  },
  {
    id: "warrington-boy-outside-the",
    title: "Warrington Boy Outside The Grid",
    soundId: "2250475136",
    slug: "warrington-boy-outside-the",
    image: "/images/tracks/warrington-boy-outside-the.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/warrington-boy-outside-the",
    recorded: "January 2026",
  },
  {
    id: "hidden-circuits-of-the-one",
    title: "Hidden Circuits of the One",
    soundId: "2250473330",
    slug: "hidden-circuits-of-the-one",
    image: "/images/tracks/hidden-circuits-of-the-one.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/hidden-circuits-of-the-one",
    recorded: "January 2026",
  },
  {
    id: "michael-my-lil-legend",
    title: "Michael, My Lil Legend",
    soundId: "2250472553",
    slug: "michael-my-lil-legend",
    image: "/images/tracks/michael-my-lil-legend.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/michael-my-lil-legend",
    recorded: "January 2026",
  },
  {
    id: "el-chapo-lev",
    title: "El Chapo Lev",
    soundId: "2250471800",
    slug: "el-chapo-lev",
    image: "/images/tracks/el-chapo-lev.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/el-chapo-lev",
    recorded: "January 2026",
  },
  {
    id: "cardboard-kingdom",
    title: "Cardboard Kingdom",
    soundId: "2250471083",
    slug: "cardboard-kingdom",
    image: "/images/tracks/cardboard-kingdom.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/cardboard-kingdom",
    recorded: "January 2026",
  },
  {
    id: "amy-all-out-of-love",
    title: "Amy (All Out of Love)",
    soundId: "2250468779",
    slug: "amy-all-out-of-love",
    image: "/images/tracks/amy-all-out-of-love.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/amy-all-out-of-love",
    recorded: "January 2026",
  },
  {
    id: "funk-in-the-forest",
    title: "Funk in the Forest",
    soundId: "2250467834",
    slug: "funk-in-the-forest",
    image: "/images/tracks/funk-in-the-forest.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/funk-in-the-forest",
    recorded: "January 2026",
  },
  {
    id: "paper-tigers-in-red-ties",
    title: "Paper Tigers in Red Ties",
    soundId: "2250466964",
    slug: "paper-tigers-in-red-ties",
    image: "/images/tracks/paper-tigers-in-red-ties.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/paper-tigers-in-red-ties",
    recorded: "January 2026",
  },
  {
    id: "still-on-the-graft",
    title: "Still on the Graft",
    soundId: "2250465074",
    slug: "still-on-the-graft",
    image: "/images/tracks/still-on-the-graft.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/still-on-the-graft",
    recorded: "January 2026",
  },
  {
    id: "trevor-the-beat-creator",
    title: "Trevor The Beat Creator",
    soundId: "2250463943",
    slug: "trevor-the-beat-creator",
    image: "/images/tracks/trevor-the-beat-creator.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/trevor-the-beat-creator",
    recorded: "January 2026",
  },
  {
    id: "beyond-the-body",
    title: "Beyond The Body",
    soundId: "2250463271",
    slug: "beyond-the-body",
    image: "/images/tracks/beyond-the-body.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/beyond-the-body",
    recorded: "January 2026",
  },
  {
    id: "critical-mass-in-warrington",
    title: "Critical Mass in Warrington",
    soundId: "2250461414",
    slug: "critical-mass-in-warrington",
    image: "/images/tracks/critical-mass-in-warrington.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/critical-mass-in-warrington",
    recorded: "January 2026",
  },
  {
    id: "still-not-retiring-in",
    title: "Still Not Retiring in Warrington",
    soundId: "2250459854",
    slug: "still-not-retiring-in",
    image: "/images/tracks/still-not-retiring-in.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/still-not-retiring-in",
    recorded: "January 2026",
  },
  {
    id: "i-never-left-you-i-left-the-i",
    title: "I Never Left You, I Left The I",
    soundId: "572651154",
    slug: "i-never-left-you-i-left-the-i",
    image: "/images/tracks/i-never-left-you-i-left-the-i.jpg",
    permalink: "https://soundcloud.com/esoteric_vibrations/i-never-left-you-i-left-the-i",
    recorded: "February 2019",
  },
];
