#!/usr/bin/env node
/**
 * Build the lock-screen stream files: a 128 kbps MP3 per master, uploaded to
 * the (private) Blob store under streams/<slug>.mp3. The paid raw masters stay
 * at masters/<slug>.mp3 and are never touched or exposed by this script.
 *
 *   node scripts/transcode-streams.mjs [--masters <dir>] [--out <dir>] [--upload] [--only slug,slug]
 *
 *   --masters  local folder of <slug>.mp3 masters; any missing one is fetched
 *              from Blob (masters/<slug>.mp3) with BLOB_READ_WRITE_TOKEN.
 *   --out      where the stream files are written (default: $TMPDIR/atman-streams).
 *   --upload   put each stream to Blob (private, streams/<slug>.mp3).
 *
 * Always rewrites src/lib/stream-manifest.ts with the slugs that have a
 * stream on disk (uploaded when --upload), so the player knows which tablets
 * can use the native <audio> path. Needs ffmpeg with libmp3lame.
 */
import { spawn } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, readFile, stat, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
export const STREAM_BITRATE_KBPS = 128;
export const STREAM_PREFIX = "streams/";
const SLUG_RE = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;

/** @param {string} slug */
export function streamBlobPath(slug) {
  if (!SLUG_RE.test(slug)) throw new Error(`invalid slug: ${slug}`);
  return `${STREAM_PREFIX}${slug}.mp3`;
}

/**
 * ffmpeg arguments: drop the master's tags (Suno ids etc.), CBR 128k MP3 at
 * 44.1 kHz with a Xing header so Safari seeks accurately.
 * @param {string} input @param {string} output @param {{ title: string, bitrateKbps?: number }} opts
 */
export function ffmpegArgs(input, output, opts) {
  return [
    "-hide_banner", "-loglevel", "error", "-y",
    "-i", input,
    "-map", "0:a:0", "-map_metadata", "-1",
    "-c:a", "libmp3lame", "-b:a", `${opts.bitrateKbps ?? STREAM_BITRATE_KBPS}k`,
    "-ar", "44100", "-ac", "2", "-write_xing", "1",
    "-id3v2_version", "3",
    "-metadata", `title=${opts.title}`,
    "-metadata", "artist=Atman",
    "-metadata", "comment=Atman Music stream (atmanmusic.app)",
    output,
  ];
}

/** @param {string[]} slugs */
export function manifestSource(slugs) {
  const sorted = [...new Set(slugs)].sort();
  return `// Generated by scripts/transcode-streams.mjs — do not edit by hand.
// Tablets with a ${STREAM_BITRATE_KBPS} kbps stream at streams/<slug>.mp3 (private Blob).
export const STREAM_BITRATE_KBPS = ${STREAM_BITRATE_KBPS};

export const STREAM_SLUGS: readonly string[] = [
${sorted.map((s) => `  "${s}",`).join("\n")}
];
`;
}

/**
 * Catalogue entries with a paid master: { slug, title }.
 * @param {string} source
 * @returns {{ slug: string, title: string }[]}
 */
export function masterTracks(source) {
  const out = [];
  const blocks = source.split(/\n\s{2}\{\n/).slice(1);
  for (const block of blocks) {
    const title = /\btitle:\s*"((?:[^"\\]|\\.)*)"/.exec(block)?.[1];
    const key = /\bdownloadKey:\s*"masters\/([^"]+)\.mp3"/.exec(block)?.[1];
    if (title && key) out.push({ slug: key, title: title.replace(/\\"/g, '"') });
  }
  return out;
}

/** @param {string[]} argv @param {string} name */
function arg(argv, name) {
  const i = argv.indexOf(name);
  return i >= 0 ? argv[i + 1] : undefined;
}

/** @param {string} cmd @param {string[]} args @returns {Promise<void>} */
function run(cmd, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, { stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    child.stderr.on("data", (d) => (err += d));
    child.on("error", reject);
    child.on("close", (code) => (code === 0 ? resolve() : reject(new Error(`${cmd} exited ${code}: ${err.trim()}`))));
  });
}

/** @param {string} slug @param {string} dest @param {string} token */
async function fetchMaster(slug, dest, token) {
  const { get } = await import("@vercel/blob");
  const result = await get(`masters/${slug}.mp3`, { access: "private", token });
  if (!result || result.statusCode !== 200 || !result.stream) throw new Error(`master missing in Blob: ${slug}`);
  await writeFile(dest, Buffer.from(await new Response(result.stream).arrayBuffer()));
}

async function main(argv = process.argv.slice(2)) {
  const token = process.env.BLOB_READ_WRITE_TOKEN;
  const mastersDir = arg(argv, "--masters") ?? join(tmpdir(), "atman-masters");
  const outDir = arg(argv, "--out") ?? join(tmpdir(), "atman-streams");
  const only = arg(argv, "--only")?.split(",").filter(Boolean);
  const upload = argv.includes("--upload");
  if (upload && !token) throw new Error("--upload needs BLOB_READ_WRITE_TOKEN");
  await mkdir(mastersDir, { recursive: true });
  await mkdir(outDir, { recursive: true });

  const catalog = await readFile(join(root, "src/lib/soundcloud-tracks.ts"), "utf8");
  let tracks = masterTracks(catalog);
  if (only) tracks = tracks.filter((t) => only.includes(t.slug));
  const put = upload ? (await import("@vercel/blob")).put : null;

  /** @type {string[]} */
  const done = [];
  let bytes = 0;
  const queue = [...tracks];
  await Promise.all(
    Array.from({ length: 4 }, async () => {
      while (queue.length) {
        const t = queue.shift();
        if (!t) break;
        const master = join(mastersDir, `${t.slug}.mp3`);
        if (!existsSync(master)) {
          if (!token) throw new Error(`no local master for ${t.slug} and no BLOB_READ_WRITE_TOKEN`);
          await fetchMaster(t.slug, master, token);
        }
        const out = join(outDir, `${t.slug}.mp3`);
        await run("ffmpeg", ffmpegArgs(master, out, { title: t.title }));
        const size = (await stat(out)).size;
        bytes += size;
        if (put) {
          await put(streamBlobPath(t.slug), await readFile(out), {
            access: "private",
            addRandomSuffix: false,
            allowOverwrite: true,
            contentType: "audio/mpeg",
            cacheControlMaxAge: 60 * 60 * 24 * 365,
            token,
          });
        }
        done.push(t.slug);
        console.log(`[streams] ${t.slug} ${(size / 1e6).toFixed(2)} MB${put ? " uploaded" : ""}`);
      }
    }),
  );

  // Without --only the manifest is exactly what was built; with --only it adds.
  let slugs = done;
  if (only) {
    try {
      const prev = await readFile(join(root, "src/lib/stream-manifest.ts"), "utf8");
      slugs = [...new Set([...[...prev.matchAll(/^\s+"([a-z0-9-]+)",$/gm)].map((m) => m[1]), ...done])];
    } catch {
      /* first run */
    }
  }
  await writeFile(join(root, "src/lib/stream-manifest.ts"), manifestSource(slugs));
  console.log(`[streams] ${done.length} streams, ${(bytes / 1e6).toFixed(1)} MB → manifest has ${slugs.length}`);
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  main().catch((err) => {
    console.error(`[streams] ${err?.message || err}`);
    process.exit(1);
  });
}
