/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DownloadCancelRouteImport } from './routes/download/cancel'
import { Route as DownloadSuccessRouteImport } from './routes/download/success'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiDownloadsTokenRouteImport } from './routes/api/downloads/$token'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadCancelRoute = DownloadCancelRouteImport.update({
  id: '/download/cancel',
  path: '/download/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadSuccessRoute = DownloadSuccessRouteImport.update({
  id: '/download/success',
  path: '/download/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadsTokenRoute = ApiDownloadsTokenRouteImport.update({
  id: '/api/downloads/$token',
  path: '/api/downloads/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/download/cancel': typeof DownloadCancelRoute
  '/download/success': typeof DownloadSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$token': typeof ApiDownloadsTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/download/cancel': typeof DownloadCancelRoute
  '/download/success': typeof DownloadSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$token': typeof ApiDownloadsTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/download/cancel': typeof DownloadCancelRoute
  '/download/success': typeof DownloadSuccessRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/downloads/$token': typeof ApiDownloadsTokenRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/download/cancel'
    | '/download/success'
    | '/api/auth/$'
    | '/api/downloads/$token'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/download/cancel'
    | '/download/success'
    | '/api/auth/$'
    | '/api/downloads/$token'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/download/cancel'
    | '/download/success'
    | '/api/auth/$'
    | '/api/downloads/$token'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  DownloadCancelRoute: typeof DownloadCancelRoute
  DownloadSuccessRoute: typeof DownloadSuccessRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadsTokenRoute: typeof ApiDownloadsTokenRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/cancel': {
      id: '/download/cancel'
      path: '/download/cancel'
      fullPath: '/download/cancel'
      preLoaderRoute: typeof DownloadCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/success': {
      id: '/download/success'
      path: '/download/success'
      fullPath: '/download/success'
      preLoaderRoute: typeof DownloadSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/downloads/$token': {
      id: '/api/downloads/$token'
      path: '/api/downloads/$token'
      fullPath: '/api/downloads/$token'
      preLoaderRoute: typeof ApiDownloadsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  DownloadCancelRoute: DownloadCancelRoute,
  DownloadSuccessRoute: DownloadSuccessRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadsTokenRoute: ApiDownloadsTokenRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
