/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as EbookRouteImport } from './routes/ebook'
import { Route as BowlsRouteImport } from './routes/bowls'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiEbookHitRouteImport } from './routes/api/ebook/hit'
import { Route as ApiMastersDownloadRouteImport } from './routes/api/masters/download'
import { Route as ApiStreamSlugRouteImport } from './routes/api/stream/$slug'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const EbookRoute = EbookRouteImport.update({
  id: '/ebook',
  path: '/ebook',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlsRoute = BowlsRouteImport.update({
  id: '/bowls',
  path: '/bowls',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEbookHitRoute = ApiEbookHitRouteImport.update({
  id: '/api/ebook/hit',
  path: '/api/ebook/hit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMastersDownloadRoute = ApiMastersDownloadRouteImport.update({
  id: '/api/masters/download',
  path: '/api/masters/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamSlugRoute = ApiStreamSlugRouteImport.update({
  id: '/api/stream/$slug',
  path: '/api/stream/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/ebook': typeof EbookRoute
  '/bowls': typeof BowlsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebook/hit': typeof ApiEbookHitRoute
  '/api/masters/download': typeof ApiMastersDownloadRoute
  '/api/stream/$slug': typeof ApiStreamSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/ebook': typeof EbookRoute
  '/bowls': typeof BowlsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebook/hit': typeof ApiEbookHitRoute
  '/api/masters/download': typeof ApiMastersDownloadRoute
  '/api/stream/$slug': typeof ApiStreamSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/download': typeof DownloadRoute
  '/ebook': typeof EbookRoute
  '/bowls': typeof BowlsRoute
  '/login': typeof LoginRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/ebook/hit': typeof ApiEbookHitRoute
  '/api/masters/download': typeof ApiMastersDownloadRoute
  '/api/stream/$slug': typeof ApiStreamSlugRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/download'
    | '/ebook'
    | '/bowls'
    | '/login'
    | '/api/auth/$'
    | '/api/ebook/hit'
    | '/api/masters/download'
    | '/api/stream/$slug'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/download'
    | '/ebook'
    | '/bowls'
    | '/login'
    | '/api/auth/$'
    | '/api/ebook/hit'
    | '/api/masters/download'
    | '/api/stream/$slug'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/download'
    | '/ebook'
    | '/bowls'
    | '/login'
    | '/api/auth/$'
    | '/api/ebook/hit'
    | '/api/masters/download'
    | '/api/stream/$slug'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DownloadRoute: typeof DownloadRoute
  EbookRoute: typeof EbookRoute
  BowlsRoute: typeof BowlsRoute
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiEbookHitRoute: typeof ApiEbookHitRoute
  ApiMastersDownloadRoute: typeof ApiMastersDownloadRoute
  ApiStreamSlugRoute: typeof ApiStreamSlugRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ebook': {
      id: '/ebook'
      path: '/ebook'
      fullPath: '/ebook'
      preLoaderRoute: typeof EbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowls': {
      id: '/bowls'
      path: '/bowls'
      fullPath: '/bowls'
      preLoaderRoute: typeof BowlsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ebook/hit': {
      id: '/api/ebook/hit'
      path: '/api/ebook/hit'
      fullPath: '/api/ebook/hit'
      preLoaderRoute: typeof ApiEbookHitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/masters/download': {
      id: '/api/masters/download'
      path: '/api/masters/download'
      fullPath: '/api/masters/download'
      preLoaderRoute: typeof ApiMastersDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream/$slug': {
      id: '/api/stream/$slug'
      path: '/api/stream/$slug'
      fullPath: '/api/stream/$slug'
      preLoaderRoute: typeof ApiStreamSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DownloadRoute: DownloadRoute,
  EbookRoute: EbookRoute,
  BowlsRoute: BowlsRoute,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiEbookHitRoute: ApiEbookHitRoute,
  ApiMastersDownloadRoute: ApiMastersDownloadRoute,
  ApiStreamSlugRoute: ApiStreamSlugRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
